### PR TITLE
docs: make it clear who is maintaining this plugin

### PR DESCRIPTION
**Pull request by regisb**

### CODE REVIEW

**Comment by regisb** [comment]
@overhangio/tutor-maintainers I'd like you to open a similar pull request in your respective repositories. In particular:

1. Add yourself to the README, in a "troubleshooting" section.
2. Update the setup.py discussion link to point to discuss.openedx.org.
3. Add the "maintainer" field (and optionally the "maintainer_email") to the setup.py.

Feel free to link to your company or your personal website.

The goal of this change is to clarify and better acknowledge the work of maintainers. We can discuss here the specific wording that we would like to use.

**Comment by regisb** [comment]
hello @overhangio/tutor-maintainers?

**Comment by kdmccormick** [comment]
on it @regisb

**Comment by kdmccormick** [comment]
Plugin cookiecutter is all set: https://github.com/overhangio/cookiecutter-tutor-plugin/commit/ea34f251303ca1bcc1142275be1a5067f91aa219

**Comment by arbrandes** [comment]
Adding https://github.com/overhangio/tutor-mfe/issues/68 to TODO list.

**Comment by jfavellar90** [comment]
PR ready in https://github.com/overhangio/tutor-notes/pull/17

**Pull request merged**
